project:
  type: website
  output-dir: docs

website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - introduction.qmd
      - section3.qmd
      
format:
  html:
    theme: zephyr
    mainfont: arial
    fontsize: 1rem
    linkcolor: "#C8102E"
    css: styles.css
    toc: true



