project:
  type: website
  output-dir: docs
  resources:
   - styles.css

website:
  title: "<img src='milwaukeelogo.png' style='height:40px;'>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - section1.qmd
      - section2.qmd
      - section3.qmd
      - section4.qmd
      - section5.qmd
      
format:
  html:
    theme: zephyr
    mainfont: arial
    fontsize: 1rem
    linkcolor: "#C8102E"
    css: styles.css
    toc: true



